dynamic lates_post = [
  {
    "image":"assets/images/software-developement.jpg",
    "Job_title":"Flutter Developer",
    "company_name":"SyntaxRoot",
    "Location":"Lahore",
    "Post_date":"Apr 27, 2022",
  },
  {
    "image":"assets/images/Absolute Ideas.png",
    "Job_title":"React Native Developer",
    "company_name":"Frank Software",
    "Location":"Multan",
    "Post_date":"March 17, 2022",
  },
  {
    "image":"assets/images/App-development.jpg",
    "Job_title":"Web Developer",
    "company_name":"Mature Software",
    "Location":"Islamabad",
    "Post_date":"May 24, 2022",
  },
  {
    "image":"assets/images/Developers Thrill.png",
    "Job_title":"Android Developer",
    "company_name":"Pure Logics",
    "Location":"Okara",
    "Post_date":"June 12, 2022",
  },
  {
    "image":"assets/images/App-development.jpg",
    "Job_title":"Backend Developer",
    "company_name":"Content Software",
    "Location":"Lahore",
    "Post_date":"Aug 27, 2022",
  },
  {
    "image":"assets/images/Software Island.png",
    "Job_title":"Flutter Developer",
    "company_name":"SyntaxRoot",
    "Location":"Lahore",
    "Post_date":"Apr 27, 2022",
  },
  {
    "image":"assets/images/Absolute Ideas.png",
    "Job_title":"React Native Developer",
    "company_name":"Frank Software",
    "Location":"Multan",
    "Post_date":"March 17, 2022",
  },
  {
    "image":"assets/images/App-development.jpg",
    "Job_title":"Web Developer",
    "company_name":"Mature Software",
    "Location":"Islamabad",
    "Post_date":"May 24, 2022",
  },
  {
    "image":"assets/images/Developers Thrill.png",
    "Job_title":"Android Developer",
    "company_name":"Pure Logics",
    "Location":"Okara",
    "Post_date":"June 12, 2022",
  },
  {
    "image":"assets/images/Software Island.png",
    "Job_title":"Backend Developer",
    "company_name":"Content Software",
    "Location":"Lahore",
    "Post_date":"Aug 27, 2022",
  },

];